package ir.stts.transferamount.entities.enums;

import lombok.Getter;

@Getter
public enum RtgsTransferType {
    DIRECT,
    INIT,
    TRANSFER,
    STATUS_WITH_CORRELATION_ID,
    STATUS_WITH_CLIENT_CORRELATION_ID,
    INIT_WITHOUT_WITHDRAW,
    TRANSFER_WITHOUT_WITHDRAW,
    DIRECT_WITHOUT_WITHDRAW,
    STATUS_WITHOUT_WITHDRAW_WITH_CORRELATION_ID,
    STATUS_WITHOUT_WITHDRAW_WITH_CLIENT_CORRELATION_ID;
}
